name: Build and Push to GHCR

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Calculate Tags
        env:
          ref: ${{ github.ref }}
          repo: ${{ github.repository }}
        run: |
          ref=${ref##*/}
          repo=${repo,,}
          image=ghcr.io/$repo
          if [[ $ref == master ]]; then
            tags=$image:unstable
          elif [[ $ref =~ ^([0-9.]+)-((([0-9]+[.])[0-9]+[.])([.][0-9+])*)$ ]]; then
            upstream=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[3]}x
            major=${BASH_REMATCH[4]}x
            tags=$image:latest,$image:$ref,$image:$upstream-$minor,$image:$upstream-$major,$image:$upstream
          else
            echo "Bad tag: $ref"
            exit 1
          fi

          echo "$tags"
          echo "build_tags=$tags" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.build_tags }}
